language: bash
solution: NValidations.sln
os: windows
install:
  - choco install nuget.commandline
  - nuget restore NValidations.sln
script:
  - dotnet.exe build -c Release
  - dotnet.exe test -c Release NValidations.Tests/NValidations.Tests.csproj
  - nuget pack -properties Configuration=Release NValidations/
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_KEY
    file: Vraiment.NValidations.$TRAVIS_TAG.nupkg
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script:
      - nuget push ./Vraiment.NValidations.$TRAVIS_TAG.nupkg -ApiKey $NUGET_ORG_KEY
    on:
      tags: true
